whoRecentlySaid/config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
    resources :comments
  end

  resources :profiles do
    resources :comments
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

whoRecentlySaid/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

whoRecentlySaid/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :conversation
  belongs_to :profile
end

whoRecentlySaid/app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true, length: {minimum: 10}
end

whoRecentlySaid/app/models/profile.rb
class Profile < ApplicationRecord
  has_many :comments
  validates :firstName, presence: true, length: {minimum:2}
  validates :lastName, presence: true, length: {minimum:2}
  validates :password, presence: true, length: {minimum:2}
end

whoRecentlySaid/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

whoRecentlySaid/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @conversation = Conversation.find(params[:conversation_id])
    @comment = @conversation.comments.create(comment_params)
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation = Conversation.find(params[:conversation_id])
    @comment = @conversation.comments.find(params[:id])
    @comment.destroy

    redirect_to conversation_path(@conversation)
  end

  private
  def comment_params
    params.require(:comment).permit(:profile, :body)
  end
end

whoRecentlySaid/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def index
    @conversations = Conversation.all
  end

  def show
    @conversation = Conversation.find(params[:id])
  end

  def new
    @conversation = Conversation.new
  end

  def edit
    @conversation = Conversation.find(params[:id])
  end

  def create
    @conversation = Conversation.new(conversation_params)

    if @conversation.save
      redirect_to @conversation
    else
      render 'new'
    end
  end

  def update
    @conversation = Conversation.find(params[:id])

    if @conversation.update(conversation_params)
      redirect_to @conversation
    else
      render 'edit'
    end
  end

  def destroy
    @conversation = Article.find(params[:id])
    @conversation.destroy

    redirect_to conversations_path
  end

  private
  def conversation_params
    params.require(:conversation).permit(:title, :description)
  end
end

whoRecentlySaid/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to @profile
    else
      render 'new'
    end
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update(profile_params)
      redirect_to @profile
    else
      render 'edit'
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    redirect_to profiles_path
  end

  private
  def profile_params
    params.require(:profile).permit(:firstName, :lastName, :email, :password)
  end
end

whoRecentlySaid/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

whoRecentlySaid/app/helpers/application_helper.rb
module ApplicationHelper
end

whoRecentlySaid/app/helpers/comments_helper.rb
module CommentsHelper
end

whoRecentlySaid/app/helpers/conversations_helper.rb
module ConversationsHelper
end

whoRecentlySaid/app/helpers/profiles_helper.rb
module ProfilesHelper
end

whoRecentlySaid/app/helpers/welcome_helper.rb
module WelcomeHelper
end

whoRecentlySaid/app/views/comments/_comment.html.erb
<P>
  <strong>Profile:</strong>
  <%= comment.profile %>
</p>
<p>
  <strong>comment:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Delete', [comment.conversation, comment], method: :delete, data: {confirm: 'Are you sure?'} %>
</p>

whoRecentlySaid/app/views/comments/_form.html.erb
<%= form_for([@conversation, @conversation.comments.build]) do |f| %>
<p>
    <%= f.label :profile %>
    <%= f.text_field :profile %>
</p>
<p>
    <%= f.label :body %>
    <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

whoRecentlySaid/app/views/conversations/_form.html.erb
<%= form_for @conversation do |f| %>
<% if @conversation.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>
  </div>
  <ul>
    <% @conversation.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<p>
    <%= f.label :title %>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :description %>
    <%= f.text_area :description %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

whoRecentlySaid/app/views/conversations/edit.html.erb
<h1>Edit conversation</h1>
<%= render 'form' %>
<%= link_to 'Home', conversations_path %>

whoRecentlySaid/app/views/conversations/index.html.erb
<h1>Listing conversations</h1>
<%= link_to 'New', new_conversation_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th colspan="2"></th>
  </tr>
  <% @conversations.each do |conv| %>
  <tr>
    <td><%= conv.title %></td>
    <td><%= conv.description %></td>
    <td><%= link_to 'Show', conversation_path(conv) %></td>
    <td><%= link_to 'Edit', edit_conversation_path(conv) %></td>
    <td><%= link_to 'Destroy', conversation_path(conv), method: :delete, data: {confirm: 'Are you sure?'}%></td>
  </tr>
  <% end %>
</table>

whoRecentlySaid/app/views/conversations/new.html.erb
<h1>New conversation</h1>
<%= render 'form' %>
<%= link_to 'Home', conversations_path %>

whoRecentlySaid/app/views/conversations/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @conversation.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @conversation.description %>
</p>

<h2>Comments:</h2>
<%= render @conversation.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_conversation_path(@conversation) %>
<%= link_to 'Home', conversations_path %>

whoRecentlySaid/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhoRecentlySaid</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

whoRecentlySaid/app/views/profiles/_form.html.erb
<%= form_for :profile, url: profiles_path do |f| %>

<% if @profile.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@profile.errors.count, 'error') %> prohibited this article from being saved:
    </h2>
    <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= f.label :firstName %>
    <%= f.text_field :firstName %>
  </p>
  <p>
    <%= f.label :lastName %>
    <%= f.text_field :lastName %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
      <%= f.submit %>
  </p>
<% end %>

whoRecentlySaid/app/views/profiles/edit.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back to Profiles', profiles_path %>

whoRecentlySaid/app/views/profiles/index.html.erb
<h1>Listing Profiles</h1>

<%= link_to 'New', new_profile_path %>
<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>email</th>
    <th>password</th>
  </tr>
  <% @profiles.each do |profile|%>
  <tr>
    <td><%= profile.firstName %></td>
    <td><%= profile.lastName %></td>
    <td><%= profile.email %></td>
    <td><%= profile.password %></td>
    <td><%= link_to 'Show', profile_path(profile) %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile_path(profile), method: :delete, data: {confirm: 'Are you sure?'}%></td>
  </tr>
  <% end %>
</table>

whoRecentlySaid/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back to Profiles', profiles_path %>

whoRecentlySaid/app/views/profiles/show.html.erb
<h1>Show profile</h1>
<p>
  <strong>First Name:</strong>
  <%= @profile.firstName %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @profile.lastName %>
</p>
<p>
  <strong>Email:</strong>
  <%= @profile.email %>
</p>
<p>
  <strong>Password:</strong>
  <%= @profile.password %>
</p>

<%= link_to 'Back to Profiles', profiles_path %>

whoRecentlySaid/app/views/welcome/index.html.erb
<h1>Who Recently Said</h1>
<%= link_to 'show conversations', conversations_path %>